name: Build and test
on:
  pull_request:
  workflow_dispatch:

env:
  STACK_ARGS: --resolver=lts-15.11

jobs:
  build-and-run-unit-tests:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2, actions/
      
      - name: Setup
        run: stack $STACK_ARGS --no-terminal setup -j 2
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack-work
          key: ${{ runner.os }}-build-deps-${{ hashFiles('stack.yaml', 'stack.yaml.lock') }}
          restore-keys: |
             ${{ runner.os }}-build-deps-
          
      - name: Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: stack $STACK_ARGS --no-terminal build -j 2 --dependencies-only --test --no-run-tests --haddock --no-haddock-deps --fast
      - name: Build
        run: stack $STACK_ARGS --no-terminal build -j 2 --fast
      - name: Test
        run: stack $STACK_ARGS test --no-terminal --haddock --no-haddock-deps --fast
      - name: Install
        run: stack $STACK_ARGS install

