name: Build and test
on:
  pull_request:
    branches:
      [master]
  workflow_dispatch:

jobs:
  build-rome:
    runs-on: macos-11
    env:
      STACK_ARGS: --resolver=lts-15.11
    steps:
      - uses: actions/checkout@v2
      - name: Cache stack
        id: cache-stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-cache-stack-${{ hashFiles('stack.yaml', 'stack.yaml.lock') }}
          restore-keys: |
             ${{ runner.os }}-cache-stack
      - name: Setup
        if: steps.cache-stack.outputs.cache-hit != 'true'
        run: stack $STACK_ARGS --no-terminal setup
      - name: Dependencies
        if: steps.cache-stack.outputs.cache-hit != 'true'
        run: stack $STACK_ARGS --no-terminal build --dependencies-only --fast
      - name: Build
        run: stack $STACK_ARGS --no-terminal build --test --no-run-tests --fast
      - name: Test
        run: stack $STACK_ARGS test --no-terminal --fast
      - name: Install
        run: stack $STACK_ARGS install
      - name: Upload Rome Binary
        uses: actions/upload-artifact@v2
        with:
          name: rome-binary
          path: ~/.local/bin/rome

  integration-tests-static-frameworks:
    needs: build-rome
    runs-on: macos-11
    steps:
      - name: Download Rome Binary
        uses: actions/download-artifact@v2
        with:
          name: rome-binary
      - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - run: |
          ls -la $HOME/.local/bin
          rome --version
    
  
  integration-tests-dynamic-frameworks:
    needs: build-rome
    runs-on: macos-11
    steps:
      - name: Download Rome Binary
        uses: actions/download-artifact@v2
        with:
          name: rome-binary
      - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - run: |
          ls -la $HOME/.local/bin
          rome --version
    
    
  integration-tests-current-framework:
    needs: build-rome
    runs-on: macos-11
    steps:
      - name: Download Rome Binary
        uses: actions/download-artifact@v2
        with:
          name: rome-binary
      - run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - run: |
          ls -la $HOME/.local/bin
          rome --version
    

